#!/usr/bin/env bash

echo "== deploy cfn ec2"

STACK_NAME="cfn-ec2"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy/index.html
aws cloudformation deploy \
    --template-file template.yaml \
    --capabilities CAPABILITY_NAMED_IAM \
    --no-execute-changeset \
    --stack-name $STACK_NAME

# Use the console from here to create your AWS Auto Scaling recommendations