AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: MySecret
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
        -
          Key: SecretFor
          Value: Demo
  DBInstanceSecretAttachment:
    Type: 'AWS::SecretsManager::SecretTargetAttachment'
    Properties:
      SecretId: !Ref 