#!/usr/bin/env bash

# Create a VPC w/ subnets
VPC_ID=$(aws ec2 create-vpc --cidr-block "10.10.0.0/16" \
    --region us-east-1 \
    --tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=PracticeVPC}]' \
    --query Vpc.VpcId \
    --output text
)

echo "VPC ID: $VPC_ID"

SUBNET_ID=$(aws ec2 create-subnet --vpc-id $VPC_ID \
    --cidr-block 10.10.0.0/20 \
    --query Subnet.SubnetId \
    --output text
)
echo "Subnet ID: $SUBNET_ID"

# Configure route table to explicity associate subnets
ROUTE_TABLE_ID=$(aws ec2 describe-route-tables \
    --filters "Name=vpc-id,Values=${VPC_ID}" \
    --query 'RouteTables[0].RouteTableId' \
    --output text
)

echo "Route Table ID: $ROUTE_TABLE_ID"

aws ec2 associate-route-table --route-table-id $ROUTE_TABLE_ID --subnet-id $SUBNET_ID

# Create Internet Gateway
IGW_ID=$(aws ec2 create-internet-gateway --query InternetGateway.InternetGatewayId --output text)
aws ec2 attach-internet-gateway --vpc-id $VPC_ID --internet-gateway-id $IGW_ID
echo "Internet Gateway ID: $IGW_ID"

# Add route to Internet Gateway
echo "Adding route to IGW..."
aws ec2 create-route --route-table-id $ROUTE_TABLE_ID --destination-cidr-block 0.0.0.0/0 --gateway-id $IGW_ID

# Create EC2 keypair
aws ec2 create-key-pair --key-name MyKeyPair --query 'KeyMaterial' --output text > MyKeyPair.pem
chmod 400 MyKeyPair.pem

# Create a SG with instance
aws cloudformation deploy \
    --template-file "template.yaml" \
    --stack-name "my-sg-stack" \
    --parameter-overrides SubnetID=$SUBNET_ID VpcID=$VPC_ID \
    --capabilities CAPABILITY_IAM

# Get the instance ID from the stack outputs
INSTANCE_ID=$(aws cloudformation describe-stack-resources \
    --stack-name "my-nacl-stack" \
    --query "StackResources[?LogicalResourceId=='MyEC2Instance'].PhysicalResourceId" \
    --output text
)

echo "The instance ID is: $INSTANCE_ID"

# Wait for instance to be running
aws ec2 wait instance-running --instance-ids $INSTANCE_ID

# Get Public IP
PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
echo "Public IP: $PUBLIC_IP"

# Test connectivity (assuming an HTTP server is running on the instance)
echo "Testing connectivity to $PUBLIC_IP..."
curl http://$PUBLIC_IP

echo "Changing protocol to modify ec2 traffic to only ssh"

# Get Security Group ID(s)
SECURITY_GROUP_IDS=$(aws ec2 describe-instances \
    --instance-ids $INSTANCE_ID \
    --query 'Reservations[0].Instances[0].SecurityGroups[*].GroupId' \
    --output text
)

# Change the SG to allow only ssh protocol
# Modify security group to only allow SSH (port 22) inbound traffic
aws ec2 authorize-security-group-ingress \
    --group-id $SECURITY_GROUP_IDS \
    --protocol tcp \
    --port 22 \
    --cidr 0.0.0.0/0

# Revoke all other ingress rules
aws ec2 revoke-security-group-ingress \
    --group-id $SECURITY_GROUP_IDS \
    --protocol -1 \
    --port all \
    --cidr 0.0.0.0/0

# Now we cannot connect
echo "Testing connectivity to $PUBLIC_IP..."
curl http://$PUBLIC_IP