AWSTemplateFormatVersion: "2010-09-09"
Description: Launch a simple EC2 for testing VPC NACL

Parameters:
  ImageID:
    Default: "ami-01b799c439fd5516a"
    Type: String
  KeyName1:
    Default: "MyKeyPair1"
    Type: String
  KeyName2:
    Default: "MyKeyPair2"
    Type: String
  SubnetID1:
    Type: String
  SubnetID2:
    Type: String
  VpcID1:
    Type: String
  VpcID2:
    Type: String

Resources:
  SSMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref SSMRole

  MyEC2Instance1: 
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: !Ref ImageID
      KeyName: !Ref KeyName1
      IamInstanceProfile: !Ref EC2InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetID1
          AssociatePublicIpAddress: true
          GroupSet:
            - Ref: InstanceSecurityGroup1
          DeleteOnTermination: true
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><body><h1>Hello from Apache on Amazon Linux 2</h1></body></html>" > /var/www/html/index.html
  MyEC2Instance2: 
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: "t2.micro"
      ImageId: !Ref ImageID
      KeyName: !Ref KeyName2
      IamInstanceProfile: !Ref EC2InstanceProfile
      SubnetId: !Ref SubnetID2
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup2
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<html><body><h1>Hello from Apache on Amazon Linux 2</h1></body></html>" > /var/www/html/index.html

  InstanceSecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref VpcID1
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  InstanceSecurityGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref VpcID2
      SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0