#!/usr/bin/env bash 

echo "== deploy sns"

STACK_NAME="sns-basic"

aws cloudformation deploy \
    --template-file template.yaml \
    --capabilities CAPABILITY_NAMED_IAM \
    --stack-name $STACK_NAME
