#!/usr/bin/env bash

# Create repo
aws ecr create-repository \
    --repository-name square

# Get login
aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 099001967703.dkr.ecr.us-east-1.amazonaws.com

# Go to console and run the commands to upload the docker image to the registry