AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Password:
    Type: String
    NoEcho: true # Hides the password from being visible in the hard code
Resources:
  MySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: MySecret
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
        -
          Key: SecretFor
          Value: Demo
  MySecretProvided:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      SecretString: !Ref Password