AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MySecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: MySecretForAppA
      GenerateSecretString:
        SecretStringTemplate: '{"username": "test-user"}'
        GenerateStringKey: "password"
        PasswordLength: 30
        ExcludeCharacters: '"@/\'
      Tags:
        -
          Key: AppName
          Value: AppA